x11:
    image: kanapi/kanapi-cli
    script:
        - ln -s /builds/jdanecki/kanapi-gui /kanapi_build/kanapi
        - mkdir -p ${HOME}/ci_src
        - cd /kanapi_build/kanapi/kanapi_system/kanapi-x11; ./install x11 ci
        - cd /kanapi_build/kanapi/kanapi_system/kanapi-x11; ./install x11 ci

x11-lib:
    image: kanapi/kanapi-cli-lib
    script:
        - rm -rf /kanapi_build/kanapi; ln -s /builds/jdanecki/kanapi-gui /kanapi_build/kanapi
        - mkdir -p ${HOME}/ci_src
        - cd /kanapi_build/kanapi/kanapi_system/kanapi-x11; ./install x11-lib ci

wx_gtk:
    image: kanapi/kanapi-x11
    script:
        - rm -rf /kanapi_build/kanapi; ln -s /builds/jdanecki/kanapi-gui /kanapi_build/kanapi
        - mkdir -p ${HOME}/ci_src
        - cd /kanapi_build/kanapi/kanapi_system/kanapi-gui; ./install gtk ci
        - cd /kanapi_build/kanapi/kanapi_system/kanapi-gui; ./install wxWidgets ci
          
qt:
    image: kanapi/kanapi-x11
    script:
        - rm -rf /kanapi_build/kanapi; ln -s /builds/jdanecki/kanapi-gui /kanapi_build/kanapi
        - mkdir -p ${HOME}/ci_src
        - cd /kanapi_build/kanapi/kanapi_system/kanapi-gui; ./install qt ci

